# NEXUS API Gateway - Kong Configuration (Declarative)
# This configuration can be used with Kong Gateway as an alternative to Nginx

_format_version: "3.0"

# Services - Backend API Gateway
services:
  - name: nexus-api-gateway
    url: http://localhost:8000
    protocol: http
    host: localhost
    port: 8000
    path: /
    retries: 3
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000

    # Routes
    routes:
      - name: gateway-root
        paths:
          - /
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        strip_path: false
        preserve_host: false

      - name: gateway-health
        paths:
          - /health
        methods:
          - GET
        strip_path: false

      - name: gateway-admin
        paths:
          - /admin
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        strip_path: false

    # Plugins for the service
    plugins:
      # Rate Limiting
      - name: rate-limiting
        config:
          minute: 100
          hour: 5000
          policy: local
          fault_tolerant: true
          hide_client_headers: false

      # CORS
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - X-API-Key
            - Authorization
          exposed_headers:
            - X-Auth-Token
            - X-RateLimit-Limit
            - X-RateLimit-Remaining
            - X-RateLimit-Reset
          credentials: true
          max_age: 3600

      # Request/Response Logging
      - name: file-log
        config:
          path: /var/log/kong/api-gateway.log
          reopen: true

      # Prometheus Metrics
      - name: prometheus
        config:
          per_consumer: true
          status_code_metrics: true
          latency_metrics: true
          bandwidth_metrics: true

      # IP Restriction (optional - configure as needed)
      # - name: ip-restriction
      #   config:
      #     allow:
      #       - 192.168.1.0/24
      #       - 10.0.0.0/8

      # Request Size Limiting
      - name: request-size-limiting
        config:
          allowed_payload_size: 10  # MB

      # Response Rate Limiting
      - name: response-ratelimiting
        config:
          limits:
            video:
              minute: 10
            image:
              minute: 100

# Global plugins
plugins:
  # Request ID
  - name: correlation-id
    config:
      header_name: X-Request-ID
      generator: uuid
      echo_downstream: true

  # Request Transformer
  - name: request-transformer
    config:
      add:
        headers:
          - X-Gateway: NEXUS
          - X-Gateway-Version: 1.0.0

  # Security Headers
  - name: response-transformer
    config:
      add:
        headers:
          - X-Frame-Options: SAMEORIGIN
          - X-Content-Type-Options: nosniff
          - X-XSS-Protection: 1; mode=block
          - Strict-Transport-Security: max-age=31536000; includeSubDomains

  # Bot Detection
  - name: bot-detection
    config:
      allow:
        - googlebot
        - bingbot
      deny:
        - badbot

# Upstreams (for load balancing)
upstreams:
  - name: nexus-gateway-upstream
    algorithm: round-robin
    hash_on: none
    hash_fallback: none
    healthchecks:
      active:
        healthy:
          interval: 5
          successes: 2
        unhealthy:
          interval: 5
          http_failures: 3
          timeouts: 3
        http_path: /health
        timeout: 3
        concurrency: 10
      passive:
        healthy:
          successes: 2
        unhealthy:
          http_failures: 3
          timeouts: 3

    targets:
      - target: localhost:8000
        weight: 100
      # Add more targets for high availability:
      # - target: localhost:8001
      #   weight: 100
      # - target: localhost:8002
      #   weight: 100

# Consumers (API Key users)
consumers:
  - username: admin
    custom_id: admin-user
    plugins:
      - name: key-auth
        config:
          key_names:
            - apikey

  - username: service-account
    custom_id: service-account-1
    plugins:
      - name: key-auth
        config:
          key_names:
            - apikey
      - name: rate-limiting
        config:
          minute: 1000
          hour: 50000

# Admin API configuration
_workspace: default
